// <auto-generated />
using System;
using Kuva.Auth.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kuva.Auth.EFMigrations.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260510200920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.AuthAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("result");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("auth_audit_logs", "identity");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_password_reset_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", "identity");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_permissions_name");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_permissions_normalized_name");

                    b.ToTable("permissions", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000001"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "orders.create",
                            Name = "orders.create",
                            NormalizedName = "ORDERS.CREATE"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000002"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "orders.read_own",
                            Name = "orders.read_own",
                            NormalizedName = "ORDERS.READ_OWN"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000003"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "orders.cancel_own",
                            Name = "orders.cancel_own",
                            NormalizedName = "ORDERS.CANCEL_OWN"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000004"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "profile.read_own",
                            Name = "profile.read_own",
                            NormalizedName = "PROFILE.READ_OWN"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000005"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "profile.update_own",
                            Name = "profile.update_own",
                            NormalizedName = "PROFILE.UPDATE_OWN"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000006"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "merchant.orders.read",
                            Name = "merchant.orders.read",
                            NormalizedName = "MERCHANT.ORDERS.READ"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000007"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "merchant.orders.update_status",
                            Name = "merchant.orders.update_status",
                            NormalizedName = "MERCHANT.ORDERS.UPDATE_STATUS"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000008"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "merchant.media.download",
                            Name = "merchant.media.download",
                            NormalizedName = "MERCHANT.MEDIA.DOWNLOAD"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000009"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "merchant.store.read",
                            Name = "merchant.store.read",
                            NormalizedName = "MERCHANT.STORE.READ"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000010"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "merchant.pricing.read",
                            Name = "merchant.pricing.read",
                            NormalizedName = "MERCHANT.PRICING.READ"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000011"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "merchant.pricing.update",
                            Name = "merchant.pricing.update",
                            NormalizedName = "MERCHANT.PRICING.UPDATE"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000012"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "merchant.operators.read",
                            Name = "merchant.operators.read",
                            NormalizedName = "MERCHANT.OPERATORS.READ"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000013"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "admin.stores.read",
                            Name = "admin.stores.read",
                            NormalizedName = "ADMIN.STORES.READ"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000014"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "admin.stores.create",
                            Name = "admin.stores.create",
                            NormalizedName = "ADMIN.STORES.CREATE"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000015"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "admin.stores.update",
                            Name = "admin.stores.update",
                            NormalizedName = "ADMIN.STORES.UPDATE"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000016"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "admin.users.read",
                            Name = "admin.users.read",
                            NormalizedName = "ADMIN.USERS.READ"
                        },
                        new
                        {
                            Id = new Guid("02000000-0000-0000-0000-000000000017"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "admin.audit.read",
                            Name = "admin.audit.read",
                            NormalizedName = "ADMIN.AUDIT.READ"
                        });
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_refresh_tokens_expires_at");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("IX_refresh_tokens_revoked_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_roles_name");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_roles_normalized_name");

                    b.ToTable("roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01000000-0000-0000-0000-000000000001"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Consumidor",
                            Name = "CONSUMER",
                            NormalizedName = "CONSUMER"
                        },
                        new
                        {
                            Id = new Guid("01000000-0000-0000-0000-000000000002"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Dono de loja",
                            Name = "STORE_OWNER",
                            NormalizedName = "STORE_OWNER"
                        },
                        new
                        {
                            Id = new Guid("01000000-0000-0000-0000-000000000003"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Operador de loja",
                            Name = "STORE_OPERATOR",
                            NormalizedName = "STORE_OPERATOR"
                        },
                        new
                        {
                            Id = new Guid("01000000-0000-0000-0000-000000000004"),
                            Active = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Administrador Kuva",
                            Name = "KUVA_ADMIN",
                            NormalizedName = "KUVA_ADMIN"
                        });
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UX_role_permissions_role_id_permission_id");

                    b.ToTable("role_permissions", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000002"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000004"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000005"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000006"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000007"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000008"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000009"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000006"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000007"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000008"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000009"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000010"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000011"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000012"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000013"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000014"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000015"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000016"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("03000000-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("02000000-0000-0000-0000-000000000017"),
                            RoleId = new Guid("01000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.StoreOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("store_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("IX_store_operators_store_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_store_operators_user_id");

                    b.HasIndex("StoreId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_store_operators_store_id_user_id");

                    b.ToTable("store_operators", "identity");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.TermsAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("accepted_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("PrivacyPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("privacy_policy_version");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("terms_version");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("terms_acceptances", "identity");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_users_email");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_users_normalized_email");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_users_status");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.UserConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("accepted_at");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("consent_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_consents", "identity");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("password_algorithm");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("PasswordUpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("password_updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_user_credentials_user_id");

                    b.ToTable("user_credentials", "identity");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_user_roles_user_id_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.AuthAuditLog", b =>
                {
                    b.HasOne("Kuva.Auth.Entities.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Kuva.Auth.Entities.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.RefreshToken", b =>
                {
                    b.HasOne("Kuva.Auth.Entities.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.RolePermission", b =>
                {
                    b.HasOne("Kuva.Auth.Entities.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kuva.Auth.Entities.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.StoreOperator", b =>
                {
                    b.HasOne("Kuva.Auth.Entities.Entities.User", "User")
                        .WithMany("StoreOperators")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.TermsAcceptance", b =>
                {
                    b.HasOne("Kuva.Auth.Entities.Entities.User", "User")
                        .WithMany("TermsAcceptances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.UserConsent", b =>
                {
                    b.HasOne("Kuva.Auth.Entities.Entities.User", "User")
                        .WithMany("UserConsents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.UserCredential", b =>
                {
                    b.HasOne("Kuva.Auth.Entities.Entities.User", "User")
                        .WithOne("Credential")
                        .HasForeignKey("Kuva.Auth.Entities.Entities.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.UserRole", b =>
                {
                    b.HasOne("Kuva.Auth.Entities.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kuva.Auth.Entities.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Kuva.Auth.Entities.Entities.User", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StoreOperators");

                    b.Navigation("TermsAcceptances");

                    b.Navigation("UserConsents");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
